# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "puphpet/ubuntu1404-x64"
  config.vm.provision :shell, :path=> "bootstrap.sh"

  config.vm.hostname = "hadoop-cluster"
  config.vm.network "forwarded_port", guest: 3306, host: 4306
  config.vm.network "forwarded_port", guest: 9002, host: 10002
  config.vm.network "forwarded_port", guest: 50070, host: 60070

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.30.10"

  config.ssh.forward_agent = true

  #config.vm.provider "virtualbox" do |vb|
  #   vb.gui = true
  
     # Use VBoxManage to customize the VM. For example to change memory:
  #   vb.customize ["modifyvm", :id, "--memory", "1024"]
  #end

end
